### PR TITLE
Translated some login messages

### PR DESCRIPTION
**Pull request by vjrj**
This PR translates some login messages. The new keys should me added to the documentation (you can see the Spanish translation as a sample).

Tested locally.

### CODE REVIEW

**Comment by vjrj** [comment]
Another key that should be translated:
`   'add replies': 'responder',`

**Comment by matteodem** [comment]
Looks cool, thanks a lot! Can you also update the  `GUIDE.md`?

**Comment by vjrj** [comment]
I added this part as comments because I don't speak German. I can use translate.google if you want... 

PS: Thanks indeed for your package

**Comment by matteodem** [comment]
This is released in `1.1.8` 🎉

**Comment by vjrj** [comment]
Nice... Updated in production. Thanks

**Pull request merged**
